base:
  random_state: 42

data_load:
  dataset_path: data/raw/iris.csv

featurize:
  processed_path: data/processed/featured_iris.csv
  target_column: species

data_split:
  test_size: 0.2
  trainset_path: data/processed/train_iris.csv
  testset_path: data/processed/test_iris.csv

train:
  model_path: models/model.joblib

evaluate:
  metrics_path: reports/metrics.json
